name: PyTest

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pygame

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set SDL to use dummy drivers
        run: |
          echo "SDL_VIDEODRIVER=dummy" >> $GITHUB_ENV
          echo "SDL_AUDIODRIVER=disk" >> $GITHUB_ENV

      - name: Run Flake8 Linting
        run: |
          flake8

      - name: Run test suite
        run: |
          pytest -v
